DeskClock: Fix crash when getting ringtone names
Due to restrictions introduced with Android 10 on device identifiers, it is no longer possible to read the default ringtone information without
privileged permissions.
When loading ringtone names, if we hit a SecurityException, assume its the default ringtone.

Crash stacktrace:

java.lang.SecurityException: getDefaultOutgoingPhoneAccount: Neither user 10135 nor current process has android.permission.READ_PRIVILEGED_PHONE_STATE.
   at android.os.Parcel.createException(Parcel.java:2071)
   at android.os.Parcel.readException(Parcel.java:2039)
   at android.os.Parcel.readException(Parcel.java:1987)
   at com.android.internal.telecom.ITelecomService$Stub$Proxy.getUserSelectedOutgoingPhoneAccount(ITelecomService.java:1468)
   at android.telecom.TelecomManager.getUserSelectedOutgoingPhoneAccount(TelecomManager.java:825)
   at android.media.RingtoneManager.getDefaultPhoneAccountHandle(RingtoneManager.java:891)
   at android.media.RingtoneManager.getActualDefaultRingtoneUri(RingtoneManager.java:785)
   at android.media.Ringtone.getTitle(Ringtone.java:242)
   at android.media.Ringtone.getTitle(Ringtone.java:225)
   at com.android.deskclock.data.RingtoneModel.getRingtoneTitle(RingtoneModel.java:187)

Change-Id: If39d4b5e33b7652c9928f4086b152a2c10cfc356